# STAT 59000 Deep Learning Assignment 1

By Sameer Hussain

In [22]:
import numpy as np
import tensorflow as tf
import pandas as pd

# Load the data

In [23]:
data = pd.read_csv(r"C:\Users\13177\Downloads\poisson_regression_data-1 (1).csv")
input_data = data.iloc[:, 1:].values
target_values = data.iloc[:, 0].values

# Prepare the inputs

In [24]:
target_values = target_values.reshape(-1, 1)
ones = np.ones((input_data.shape[0], 1))
inputs = np.concatenate([ones, input_data], axis=1)

# Initialize the weights

In [25]:
tf.random.set_seed(100)
weights = tf.Variable(tf.random.normal([6, 1]))

# Set the training parameters

In [26]:
training_epochs = 1000
learning_rate = 0.01

# Convert the inputs to tensors

In [27]:
inputs = tf.cast(inputs, dtype=tf.float32)
target_values = tf.cast(target_values, dtype=tf.float32)

# Define the loss function

In [28]:
def poisson_regression_loss(y_true, y_predicted):
    return tf.reduce_mean(y_predicted - y_true * tf.math.log(y_predicted))

# Train the model

In [29]:
optimizer = tf.optimizers.SGD(learning_rate)
for epoch in range(training_epochs):
    with tf.GradientTape() as tape:
        predicted_values = tf.exp(tf.matmul(inputs, weights))
        loss = poisson_regression_loss(target_values, predicted_values)
    gradients = tape.gradient(loss, weights)
    optimizer.apply_gradients(zip([gradients], [weights]))


# The values for 'w'.

In [30]:
weights

<tf.Variable 'Variable:0' shape=(6, 1) dtype=float32, numpy=
array([[ 0.4836764 ],
       [ 2.1146936 ],
       [-1.1351715 ],
       [ 0.73675394],
       [-0.490464  ],
       [ 0.19462398]], dtype=float32)>

# The predicted values by the model.

In [31]:
predicted_values

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[ 2.261135  ],
       [ 4.212836  ],
       [ 3.7879095 ],
       [11.194677  ],
       [ 3.1036403 ],
       [ 2.874963  ],
       [ 1.5880923 ],
       [ 2.074767  ],
       [ 9.182951  ],
       [ 3.4866667 ],
       [ 2.4384289 ],
       [ 8.827514  ],
       [12.978924  ],
       [ 2.5987327 ],
       [ 3.4687927 ],
       [ 6.094704  ],
       [ 2.4370317 ],
       [ 1.9836841 ],
       [12.809766  ],
       [ 5.7309337 ],
       [ 0.5911433 ],
       [ 2.4326434 ],
       [ 9.403785  ],
       [ 3.1749568 ],
       [10.753467  ],
       [ 3.7321506 ],
       [ 5.775544  ],
       [ 7.006454  ],
       [ 0.8970095 ],
       [ 7.940261  ],
       [ 1.7298696 ],
       [ 6.930628  ],
       [ 4.0875473 ],
       [ 0.5169279 ],
       [ 5.6352067 ],
       [ 4.344008  ],
       [ 1.7823409 ],
       [ 3.218753  ],
       [ 7.445042  ],
       [ 4.1542087 ],
       [ 1.2649941 ],
       [ 1.7257004 ],
       [ 0.58010954],
   